# Generated by Django 2.2.15 on 2020-09-01 16:13
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0131_auto_20200827_1253")]

    operations = [
        migrations.AlterUniqueTogether(
            name="awstagssummary", unique_together={("key", "cost_entry_bill", "accounts")}
        ),
        migrations.AlterUniqueTogether(
            name="azuretagssummary", unique_together={("key", "cost_entry_bill", "subscription_guid")}
        ),
        migrations.AlterUniqueTogether(
            name="ocpawstagssummary", unique_together={("key", "cost_entry_bill", "namespace", "accounts")}
        ),
        migrations.AlterUniqueTogether(
            name="ocpazuretagssummary", unique_together={("key", "cost_entry_bill", "namespace", "subscription_guid")}
        ),
    ]
